#DROP TABLE IF EXISTS staff;
#创建员工的个人信息表
CREATE TABLE staff(
	NAME VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	SEX VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	STA_NO VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	BIRTH DATETIME,
	DEPT VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	JOB VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	EDU VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	ADDRESS VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	TEL VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	introduction VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	PASSWORD VARCHAR(255) COLLATE UTF8_BIN NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

#如果该表已经存在则删除
#DROP TABLE IF EXISTS train;
#创建员工培训安排表
CREATE TABLE train(
	NAME VARCHAR(255) COLLATE UTF8_BIN,
	STA_ID VARCHAR(255) COLLATE UTF8_BIN,
	COURSE VARCHAR(255) COLLATE UTF8_BIN,
	SCORE VARCHAR(255) COLLATE UTF8_BIN,
	EVALUATE  VARCHAR(255) COLLATE UTF8_BIN,
	CHECK_TIME DATETIME
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
 

#DROP TABLE IF EXISTS course;
#创建课程表
CREATE TABLE course(
	NO VARCHAR(255) COLLATE UTF8_BIN  NOT NULL,#课程号
	NAME VARCHAR(255) COLLATE UTF8_BIN NOT NULL,#课程
	TEACHER VARCHAR(255) COLLATE UTF8_BIN NOT NULL,#老师
	INTRO VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	BOOK VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	START_TIME DATE,
	END_TIME DATE,
	CLASS_TIME VARCHAR(255) COLLATE UTF8_BIN,
    MAX_STAFFS INT(10),
	CLASS_ADDRESS VARCHAR(255) COLLATE UTF8_BIN,
    STATE VARCHAR(255) COLLATE UTF8_BIN NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
 
#DROP TABLE IF EXISTS course_state;
#选课状态
CREATE TABLE course_state(
	CODE VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	INTRO VARCHAR(255) COLLATE UTF8_BIN NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

#DROP TABLE IF EXISTS check_state;
#考核状态
CREATE TABLE check_state(
	CODE VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	INTRO VARCHAR(255) COLLATE UTF8_BIN NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

#DROP TABLE IF EXISTS dept;
#创建公司部门
CREATE TABLE dept(
	ID VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	NAME VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	ADMIN VARCHAR(255) COLLATE UTF8_BIN NOT NULL,
	INTRO VARCHAR(255) COLLATE UTF8_BIN NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=UTF8;